### ISSUE TITLE
Start working on the LamaFetcher

### ISSUE THREAD

**Issue by abbysmal** [LamaUrbain/LamaFetcher#1]
LamaFetcher will download periodically the data needed by LamaServer.
At first we will simply download latest map data from Open Street Map for Île-de-France.
@glionnet will be able to give you more information about where you can find those data.
As for how we will handle the time between download, i'm not fixed yet on the question. Maybe we can do a simple daemon that will relaunch the task every ten minutes ? Or juste do a simple program and start it via Cron… @jpdeplaix might have an idea.

**Comment by kit-ty-kate** [comment]
I guess a simple cron task and a script is enough. Well I don't know.

**Comment by abbysmal** [comment]
@Random-process Have you worked on this yet?
It might be a good start to first list the needed ressources for the APIs that you'll need to retrieve using this project. Maybe @glionnet can help on this.
Also @jpdeplaix, what is your final opinion on that ? Do we really need a full-featured OCaml application? If we use that we might be able to plug it directly into our backend, which can (maybe) be useful?
